# Generated by Django 5.0.6 on 2024-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_contact',
            name='company',
            field=models.CharField(max_length=300, verbose_name='company'),
        ),
    ]
