# Generated by Django 5.0.6 on 2024-08-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_new_contact_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_contact',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='company'),
        ),
    ]
